version = 0.1

[default.deploy.parameters]
stack_name = "bedrock-sd35-image-api"
resolve_s3 = true
s3_prefix = "bedrock-sd35-image-api"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-west-2"
